#!/bin/bash

nohup rake resque:work QUEUE=low VERBOSE=1 RAILS_ENV=production > /rails/statscrawler.com/log/low.out 2>&1 &
nohup rake resque:work QUEUE=high VERBOSE=1 RAILS_ENV=production > /rails/statscrawler.com/log/high.out 2>&1 &

