#!/bin/bash

nohup rake resque:work QUEUE=parser VERBOSE=1 RAILS_ENV=production > /rails/statscrawler.com/log/parser.out 2>&1 &
nohup rake resque:work QUEUE=analyzer VERBOSE=1 RAILS_ENV=production > /rails/statscrawler.com/log/analyzer.out 2>&1 &

